version: '3.9'

services:

  pkg-dc-gcloud-sql-proxy:
    build: .
    container_name: pkg-dc-gcloud-sql-proxy
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "127.0.0.1:13306:3306"
    # volumes:
    #   - ./mysql/files/etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    #   # - ./mysql/files/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - pkg-dc-gcloud-sql-proxy

networks:
  pkg-dc-gcloud-sql-proxy:
    driver: bridge
