services:

  pkg-dc-flask-db:
    build: ./mysql/
    env_file:
      - .flask.env
    container_name: pkg-dc-flask-db
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "127.0.0.1:13306:3306"
    volumes:
      - ./mysql/files/etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      # - ./mysql/files/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend

  # pkg-dc-flask-app:
  #   build: ./python/
  #   env_file:
  #     - .flask.env
  #   container_name: pkg-dc-flask-app
  #   volumes:
  #     - ./:/opt/python-mysql
  #   tty: true
  #   working_dir: '/opt/python-mysql'
  #   depends_on:
  #     - db

  pkg-dc-flask-nginx:
    # build: ./python/
    image: nginx:latest
    env_file:
      - .flask.env
    container_name: pkg-dc-flask-nginx
    # volumes:
    #   - ./:/opt/python-mysql
    tty: true
    # working_dir: '/opt/python-mysql'
    ports:
      - "0.0.0.0:18080:80"
    depends_on:
      - pkg-dc-flask-db


# https://docs.docker.com/compose/networking/#specify-custom-networks
networks:
  # frontend:
  #   name: pkg-dc-flask-frontend
  #   driver: custom-driver-2
  backend:
    name: pkg-dc-flask-backend
    # driver: custom-driver-1