version: '3.6'

services:

  grafana:
    image: grafana/grafana
    container_name: 22-grafana
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
  nginx:
    image: nginx
    container_name: 22-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/etc/nginx/ssl:/etc/nginx/ssl

#   wip:
#     image: grafana/grafana
#     container_name: hejda-grafana-db
#     ports:
#       - "3000:3000"
