CREATE TABLE access_log (
    uid INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    time  datetime DEFAULT NULL,
    id VARCHAR(255) DEFAULT NULL,
    level VARCHAR(255) DEFAULT NULL,
    method VARCHAR(255) DEFAULT NULL,
    uri VARCHAR(255) DEFAULT NULL,
    reqtime FLOAT UNSIGNED
);
