---
#
# roles/jq/tasks/main.yml
#

- name: get jq from page of download
  get_url: 
    url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 
    dest: /usr/local/bin/jq
    group: root
    owner: root
    mode: 755
