FROM iganarix/cld-gcloud:374.0.0-alpine

RUN wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /usr/local/bin/cloud_sql_proxy && \
    chmod +x /usr/local/bin/cloud_sql_proxy

# RUN apk add mariadb-client
